const allTasks = [
  {
    id: 1,
    title: "Task 1",
    status: "Incomplete",
    list: "Personal",
    deadline: "2022-01-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 1st task",
  },

  {
    id: 2,
    title: "Task 2",
    status: "Completed",
    list: "Work",
    deadline: "2022-02-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 2nd task",
  },

  {
    id: 3,
    title: "Task 3",
    status: "Completed",
    list: "Time for friends",
    deadline: "2022-03-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 3rd task",
  },

  {
    id: 4,
    title: "Task 4",
    status: "Incomplete",
    list: "Work",
    deadline: "2022-04-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 4th task",
  },

  {
    id: 5,
    title: "Task 5",
    status: "Incomplete",
    list: "Work",
    deadline: "2022-05-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 5th task",
  },

  {
    id: 6,
    title: "Task 6",
    status: "Completed",
    list: "Personal",
    deadline: "2022-06-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 6th task",
  },

  {
    id: 7,
    title: "Task 7",
    status: "Completed",
    list: "Health",
    deadline: "2022-07-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 7th task",
  },

  {
    id: 8,
    title: "Task 8",
    status: "Completed",
    list: "Health",
    deadline: "2022-08-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 8th task",
  },

  {
    id: 9,
    title: "Task 9",
    status: "Upcoming",
    list: "List",
    deadline: "2022-09-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 9th task",
  },

  {
    id: 10,
    title: "Task 10",
    status: "Upcoming",
    list: "Hobby",
    deadline: "2022-10-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 10th task",
  },

  {
    id: 11,
    title: "Task 11",
    status: "Upcoming",
    list: "Health",
    deadline: "2022-11-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 11th task",
  },

  {
    id: 12,
    title: "Task 12",
    status: "Upcoming",
    list: "Personal",
    deadline: "2022-12-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 12th task",
  },

  {
    id: 13,
    title: "Task 13",
    status: "Today",
    list: "Hobby",
    deadline: "2023-01-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 13th task",
  },

  {
    id: 14,
    title: "Task 14",
    status: "Today",
    list: "Hobby",
    deadline: "2023-02-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 14th task",
  },

  {
    id: 15,
    title: "Task 15",
    status: "Today",
    list: "Time for friends",
    deadline: "2023-03-15",
    priority: "high",
    assignee: "User 1",
    description: "This is 15th task",
  },
];
